const CATS={recruitment:'নিয়োগ পরীক্ষা',verification_test:'যাচাই পরীক্ষা',recent:'সাম্প্রতিক প্রশ্ন'};
let cat='verification_test',folders=[],sets=[],subjects=[],exams=[],importData=[];
const selectedIds=new Set();
const $=id=>document.getElementById(id),bn=n=>String(n??'').replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[d]),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function msg(id,t,err=false){const e=$(id);if(!e)return;e.textContent=t;e.style.color=err?'#b91c1c':'#166534'}
const CAT_BY_NAME=Object.fromEntries(Object.entries(CATS).map(([k,v])=>[v,k]));
function sourceText(x){return `${x.category||''} → ${x.question_bank_folders?.folder_name||'Folder'} → ${x.question_bank_sets?.set_name||'Set'} → প্রশ্ন নং ${bn(x.question_number||'')}`.trim()}
function categoryKey(name){return CAT_BY_NAME[name]||cat}
function selectedQuestionIds(){document.querySelectorAll('.question-check:checked').forEach(x=>selectedIds.add(Number(x.value)));return [...selectedIds].filter(Boolean)}
function syncVisibleChecks(){document.querySelectorAll('.question-check').forEach(x=>x.checked=selectedIds.has(Number(x.value)))}
function normalizeCorrect(v){const z=String(v||'').trim().toUpperCase();return ({'ক':'A','খ':'B','গ':'C','ঘ':'D','1':'A','2':'B','3':'C','4':'D'})[z]||z}

async function login(){msg('loginMsg','Login হচ্ছে...');const{error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return msg('loginMsg',error.message,true);await init()}
async function logout(){await db.auth.signOut();location.reload()}
function showPage(p){if(p==='dashboard'){location.href='dashboard.html';return}document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(p)?.classList.remove('hidden');if(p==='bank')loadBank();if(p==='exam')loadExams()}
async function init(){const{data,error}=await db.auth.getSession();if(error)return msg('loginMsg',error.message,true);if(!data.session){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}$('login').classList.add('hidden');$('app').classList.remove('hidden');$('userEmail').textContent=data.session.user.email||'';await loadSubjects();await loadBank();await loadExams();const u=new URL(location.href),section=u.searchParams.get('section');showPage(section==='exam'?'exam':'bank');const c=u.searchParams.get('category');if(c&&CATS[c]){await selectCategory(c)}if(section==='bank'){if(u.searchParams.get('folder_id')){$('filterFolder').value=u.searchParams.get('folder_id');await loadFilterSets();}if(u.searchParams.get('set_id'))$('filterSet').value=u.searchParams.get('set_id');await loadQuestions();const qid=u.searchParams.get('question_id');if(qid)setTimeout(()=>focusQuestion(qid),80)}}
async function loadSubjects(){const s=$('subject'),f=$('filterSubject');if(!s||!f)return;s.innerHTML='<option value="">বিষয় নির্বাচন করুন</option>';f.innerHTML='<option value="">সব বিষয়</option>';const{data,error}=await db.from('subjects').select('id,name').order('id');if(error){console.error(error);s.innerHTML='<option value="">বিষয় লোড হয়নি</option>';f.innerHTML='<option value="">বিষয় লোড হয়নি</option>';return msg('qmsg','Subject লোড হয়নি: '+error.message,true)}subjects=data||[];s.innerHTML='<option value="">বিষয় নির্বাচন করুন</option>'+subjects.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');f.innerHTML='<option value="">সব বিষয়</option>'+subjects.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
async function loadBank(){await loadFolders();await loadFilterFolders();await loadQuestions()}
async function selectCategory(c){cat=c;document.querySelectorAll('.cats button').forEach(b=>b.classList.remove('active'));$('cat-'+c)?.classList.add('active');$('currentCat').textContent='বর্তমান Category: '+CATS[c];await loadFolders();await loadFilterFolders()}
async function loadFolders(){const{data,error}=await db.from('question_bank_folders').select('id,folder_name').eq('sub_category',CATS[cat]).order('id');if(error)return msg('folderMsg',error.message,true);folders=data||[];$('folder').innerHTML='<option value="">Folder নির্বাচন করুন</option>'+folders.map(x=>`<option value="${x.id}">${esc(x.folder_name)}</option>`).join('');$('mapFolder').innerHTML='<option value="">Folder নির্বাচন করুন</option>'+folders.map(x=>`<option value="${x.id}">${esc(x.folder_name)}</option>`).join('');$('filterFolder').innerHTML='<option value="">সব Folder</option>'+folders.map(x=>`<option value="${x.id}">${esc(x.folder_name)}</option>`).join('');await loadSets()}
async function loadFilterFolders(){const{data,error}=await db.from('question_bank_folders').select('id,folder_name').eq('sub_category',CATS[cat]).order('id');if(error)return; $('filterFolder').innerHTML='<option value="">সব Folder</option>'+(data||[]).map(x=>`<option value="${x.id}">${esc(x.folder_name)}</option>`).join('')}
async function loadSets(){const id=$('folder').value;if(!id){sets=[];$('set').innerHTML='<option value="">Set নির্বাচন করুন</option>';return}const{data,error}=await db.from('question_bank_sets').select('id,set_name').eq('folder_id',Number(id)).order('id');if(error)return msg('folderMsg',error.message,true);sets=data||[];$('set').innerHTML='<option value="">Set নির্বাচন করুন</option>'+sets.map(x=>`<option value="${x.id}">${esc(x.set_name)}</option>`).join('')}
async function loadFilterSets(){const id=$('filterFolder').value;if(!id){$('filterSet').innerHTML='<option value="">সব Set</option>';return}const{data,error}=await db.from('question_bank_sets').select('id,set_name').eq('folder_id',Number(id)).order('id');if(error)return msg('qmsg',error.message,true);$('filterSet').innerHTML='<option value="">সব Set</option>'+(data||[]).map(x=>`<option value="${x.id}">${esc(x.set_name)}</option>`).join('')}
async function loadMapSets(){const id=$('mapFolder').value;if(!id){$('mapSet').innerHTML='<option value="">সব Set</option>';return}const{data,error}=await db.from('question_bank_sets').select('id,set_name').eq('folder_id',Number(id)).order('id');if(error)return msg('mapMsg',error.message,true);$('mapSet').innerHTML='<option value="">সব Set</option>'+(data||[]).map(x=>`<option value="${x.id}">${esc(x.set_name)}</option>`).join('')}
async function createFolder(){const name=$('newFolder').value.trim();if(!name)return msg('folderMsg','Folder-এর নাম দিন',true);const{data,error}=await db.from('question_bank_folders').insert({sub_category:CATS[cat],folder_name:name}).select('id,folder_name').single();if(error)return msg('folderMsg',error.message,true);$('newFolder').value='';await loadFolders();$('folder').value=data.id;await loadSets();msg('folderMsg','✅ Folder তৈরি হয়েছে')}
async function createSet(){const folderId=$('folder').value,name=$('newSet').value.trim();if(!folderId)return msg('folderMsg','আগে Folder নির্বাচন করুন',true);if(!name)return msg('folderMsg','Set-এর নাম দিন',true);const{data,error}=await db.from('question_bank_sets').insert({folder_id:Number(folderId),set_name:name}).select('id,set_name').single();if(error)return msg('folderMsg',error.message,true);$('newSet').value='';await loadSets();$('set').value=data.id;msg('folderMsg','✅ Set তৈরি হয়েছে')}
async function addManual(){const folderId=$('folder').value,setId=$('set').value,subjectId=$('subject').value,text=$('qtext').value.trim(),a=$('a').value.trim(),b=$('b').value.trim(),c=$('c').value.trim(),d=$('d').value.trim(),correct=$('correct').value;if(!folderId||!setId)return msg('qmsg','Category, Folder ও Set নির্বাচন করুন',true);if(!subjectId||!text||!a||!b||!c||!d||!correct)return msg('qmsg','বিষয়, প্রশ্ন, চার অপশন ও সঠিক উত্তর পূরণ করুন',true);const p={folder_id:Number(folderId),set_id:Number(setId),subject_id:Number(subjectId),question_text:text,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:correct,explanation:$('explanation').value.trim()||null,question_number:$('qno').value?Number($('qno').value):null,category:CATS[cat],source_type:cat};const{error}=await db.from('questions').insert(p);if(error)return msg('qmsg',error.message,true);['qno','qtext','a','b','c','d','explanation'].forEach(x=>$(x).value='');$('correct').value='';msg('qmsg','✅ প্রশ্ন Question Bank-এ যোগ হয়েছে');await loadQuestions()}
function mode(m){$('manualBox').classList.toggle('hidden',m!=='manual');$('importBox').classList.toggle('hidden',m!=='import')}
function template(){const rows=[['question','source','option_a','option_b','option_c','option_d','correct_answer','question_number','subject','explanation','category','folder','set'],['বাংলাদেশের রাজধানী কোনটি?','বিসিএস ৪৫তম পরীক্ষা','ঢাকা','চট্টগ্রাম','রাজশাহী','খুলনা','A',1,'বাংলাদেশ','','যাচাই পরীক্ষা','','']];const ws=XLSX.utils.aoa_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Questions');XLSX.writeFile(wb,'question-import-template.xlsx')}
async function previewImport(){const f=$('file').files[0];if(!f)return msg('qmsg','CSV/Excel file নির্বাচন করুন',true);const data=XLSX.read(await f.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(data.Sheets[data.SheetNames[0]],{defval:''});importData=rows;$('preview').innerHTML=`<div class="q"><b>${bn(rows.length)}টি row পাওয়া গেছে</b><pre>${esc(JSON.stringify(rows.slice(0,5),null,2))}</pre></div>`;$('importBtn').classList.remove('hidden');msg('qmsg','Preview প্রস্তুত হয়েছে')}
function norm(v){return String(v??'').trim().toLowerCase()}
async function importRows(){let ok=0,fail=[];for(let i=0;i<importData.length;i++){const r=importData[i],category=Object.values(CATS).includes(String(r.category).trim())?String(r.category).trim():CATS[cat],folderName=String(r.folder||$('folder').selectedOptions[0]?.textContent||'').trim(),setName=String(r.set||$('set').selectedOptions[0]?.textContent||'').trim(),source=String(r.source||'').trim();if(!r.question||!source||!r.option_a||!r.option_b||!r.option_c||!r.option_d||!r.correct_answer||!folderName||!setName){fail.push(`Row ${i+2}: required field missing (question, source, 4 options, correct_answer; Folder/Set না থাকলে আগে বর্তমান Folder/Set নির্বাচন করুন)`);continue}let fr=await db.from('question_bank_folders').select('id').eq('sub_category',category).eq('folder_name',folderName).maybeSingle();if(fr.error){fail.push(`Row ${i+2}: ${fr.error.message}`);continue}let fid=fr.data?.id;if(!fid){const x=await db.from('question_bank_folders').insert({sub_category:category,folder_name:folderName}).select('id').single();if(x.error){fail.push(`Row ${i+2}: ${x.error.message}`);continue}fid=x.data.id}const sr=await db.from('question_bank_sets').select('id').eq('folder_id',fid).eq('set_name',setName).maybeSingle();let sid=sr.data?.id;if(!sid){const x=await db.from('question_bank_sets').insert({folder_id:fid,set_name:setName}).select('id').single();if(x.error){fail.push(`Row ${i+2}: ${x.error.message}`);continue}sid=x.data.id}let sub=null;if(r.subject){sub=subjects.find(x=>norm(x.name)===norm(r.subject));if(!sub){fail.push(`Row ${i+2}: Subject পাওয়া যায়নি: ${r.subject}`);continue}}const p={folder_id:fid,set_id:sid,subject_id:sub?.id||null,category,source_name:source,source_type:cat,question_number:r.question_number?Number(r.question_number):null,question_text:String(r.question).trim(),option_a:String(r.option_a).trim(),option_b:String(r.option_b).trim(),option_c:String(r.option_c).trim(),option_d:String(r.option_d).trim(),correct_answer:String(r.correct_answer).trim().toUpperCase(),explanation:String(r.explanation||'').trim()||null};const x=await db.from('questions').insert(p);if(x.error)fail.push(`Row ${i+2}: ${x.error.message}`);else ok++}msg('qmsg',`✅ ${bn(ok)}টি Import হয়েছে${fail.length?` | ❌ ${bn(fail.length)}টি ব্যর্থ`:''}`,!!fail.length);if(fail.length)$('preview').innerHTML+='<div class="q">'+fail.map(esc).join('<br>')+'</div>';await loadQuestions()}
async function loadQuestions(){let q=db.from('questions').select('id,question_text,option_a,option_b,option_c,option_d,correct_answer,explanation,question_number,category,folder_id,set_id,subjects(name),question_bank_folders(folder_name,sub_category),question_bank_sets(set_name)').order('id',{ascending:false}).limit(500);if($('filterFolder').value)q=q.eq('folder_id',Number($('filterFolder').value));if($('filterSet').value)q=q.eq('set_id',Number($('filterSet').value));if($('filterSubject').value)q=q.eq('subject_id',Number($('filterSubject').value));const term=$('search').value.trim();if(term)q=q.ilike('question_text','%'+term+'%');const{data,error}=await q;if(error)return msg('qmsg',error.message,true);const rows=data||[];$('questions').innerHTML=rows.map((x,i)=>{const displayNo=bn(i+1),correct=({A:'ক',B:'খ',C:'গ',D:'ঘ'})[x.correct_answer]||x.correct_answer,src=sourceText(x),url=`?section=bank&category=${encodeURIComponent(categoryKey(x.category))}&folder_id=${x.folder_id||''}&set_id=${x.set_id||''}&question_id=${x.id}`;return `<div class="q qb-row" id="question-${x.id}"><input type="checkbox" class="qb-check question-check" value="${x.id}"><div class="qb-content"><div><b>${displayNo}. ${esc(x.question_text)}</b></div><div>ক. ${esc(x.option_a)}<br>খ. ${esc(x.option_b)}<br>গ. ${esc(x.option_c)}<br>ঘ. ${esc(x.option_d)}</div><div class="qb-correct">সঠিক উত্তর: ${esc(correct)}</div><div class="qb-source">Source: <a href="${url}" onclick="return goToQuestion(event,'${url}')">${esc(src)}</a></div><div class="small">বিষয়: ${esc(x.subjects?.name||'')}</div>${x.explanation?`<details class="qb-explanation"><summary>ব্যাখ্যা দেখুন</summary><div>${esc(x.explanation)}</div></details>`:''}<div class="qb-actions"><button class="secondary" onclick="copyQuestion(${x.id})">📋 Copy</button><button class="secondary" onclick="openEditQuestion(${x.id})">✏️ Edit</button><button class="secondary" onclick="deleteQuestion(${x.id})">🗑️ Delete</button></div></div></div>`}).join('')||'কোনো প্রশ্ন নেই';syncVisibleChecks();$('qmsg').textContent=`${bn(rows.length)}টি প্রশ্ন প্রদর্শিত`;return rows}
function goToQuestion(e,url){if(e.ctrlKey||e.metaKey||e.shiftKey||e.button!==0)return true;e.preventDefault();history.pushState({},'',url);init();return false}
function focusQuestion(id){const el=$('question-'+id);if(!el)return;el.scrollIntoView({behavior:'smooth',block:'center'});el.style.outline='3px solid #f59e0b';el.style.background='#fff7ed';setTimeout(()=>{el.style.outline='';el.style.background=''},3500)}
async function copyQuestion(id){const{data,error}=await db.from('questions').select('id,question_text,option_a,option_b,option_c,option_d,correct_answer,subjects(name)').eq('id',id).single();if(error)return msg('qmsg',error.message,true);const correct=({A:'ক',B:'খ',C:'গ',D:'ঘ'})[data.correct_answer]||data.correct_answer;const text=`${data.question_text}\nক. ${data.option_a}\nখ. ${data.option_b}\nগ. ${data.option_c}\nঘ. ${data.option_d}\nসঠিক উত্তর: ${correct}`;try{if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(text)}else{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}msg('qmsg','✅ প্রশ্ন Copy হয়েছে')}catch(_){prompt('কপি করুন',text)}}
async function openEditQuestion(id){const{data,error}=await db.from('questions').select('id,question_text,option_a,option_b,option_c,option_d,correct_answer,explanation,question_number,subject_id,category,folder_id,set_id,question_bank_folders(folder_name),question_bank_sets(set_name)').eq('id',id).single();if(error)return msg('qmsg',error.message,true);$('editQno').value=data.question_number??'';$('editSubject').innerHTML='<option value="">বিষয় নির্বাচন করুন</option>'+subjects.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('editSubject').value=data.subject_id||'';$('editQtext').value=data.question_text||'';$('editA').value=data.option_a||'';$('editB').value=data.option_b||'';$('editC').value=data.option_c||'';$('editD').value=data.option_d||'';$('editCorrect').value=data.correct_answer||'';$('editExplanation').value=data.explanation||'';$('editMeta').textContent=`Source: ${sourceText(data)}`;$('editModal').dataset.id=id;$('editModal').classList.remove('hidden')}
function closeEditQuestion(){$('editModal').classList.add('hidden');$('editMsg').textContent=''}
async function saveEditedQuestion(){const id=Number($('editModal').dataset.id),payload={question_number:$('editQno').value?Number($('editQno').value):null,subject_id:$('editSubject').value?Number($('editSubject').value):null,question_text:$('editQtext').value.trim(),option_a:$('editA').value.trim(),option_b:$('editB').value.trim(),option_c:$('editC').value.trim(),option_d:$('editD').value.trim(),correct_answer:$('editCorrect').value,explanation:$('editExplanation').value.trim()||null};if(!id||!payload.question_text||!payload.option_a||!payload.option_b||!payload.option_c||!payload.option_d||!payload.correct_answer)return msg('editMsg','প্রশ্ন, চার অপশন ও সঠিক উত্তর পূরণ করুন',true);msg('editMsg','Save হচ্ছে...');const{error}=await db.from('questions').update(payload).eq('id',id);if(error)return msg('editMsg',error.message,true);closeEditQuestion();msg('qmsg','✅ প্রশ্ন আপডেট হয়েছে');await loadQuestions();setTimeout(()=>focusQuestion(id),80)}
async function deleteQuestion(id){if(!confirm('এই প্রশ্নটি Delete করবেন?'))return;const{error}=await db.from('questions').delete().eq('id',id);if(error)return msg('qmsg',error.message,true);msg('qmsg','✅ প্রশ্ন Delete হয়েছে');await loadQuestions()}
async function selectByCurrentSet(){const id=$('filterSet').value;if(!id)return msg('moveMsg','আগে Set filter নির্বাচন করুন',true);const{data,error}=await db.from('questions').select('id').eq('set_id',Number(id));if(error)return msg('moveMsg',error.message,true);(data||[]).forEach(x=>selectedIds.add(x.id));syncVisibleChecks();msg('moveMsg',`বর্তমান Set-এর ${bn((data||[]).length)}টি প্রশ্ন Select হয়েছে`)}
async function selectByCurrentFolder(){const id=$('filterFolder').value;if(!id)return msg('moveMsg','আগে Folder filter নির্বাচন করুন',true);const{data,error}=await db.from('questions').select('id').eq('folder_id',Number(id));if(error)return msg('moveMsg',error.message,true);(data||[]).forEach(x=>selectedIds.add(x.id));syncVisibleChecks();msg('moveMsg',`বর্তমান Folder-এর ${bn((data||[]).length)}টি প্রশ্ন Select হয়েছে`)}
function toggleAllVisibleQuestions(){const boxes=[...document.querySelectorAll('.question-check')];if(!boxes.length)return msg('moveMsg','কোনো প্রশ্ন নেই',true);const all=boxes.every(x=>selectedIds.has(Number(x.value)));boxes.forEach(x=>{const id=Number(x.value);if(all)selectedIds.delete(id);else selectedIds.add(id);x.checked=!all});msg('moveMsg',all?'সব দৃশ্যমান প্রশ্ন Unselect হয়েছে':`✅ ${bn(boxes.length)}টি দৃশ্যমান প্রশ্ন Select হয়েছে`)}
async function deleteSelectedQuestions(){const ids=selectedQuestionIds();if(!ids.length)return msg('moveMsg','আগে প্রশ্ন Select করুন',true);if(!confirm(`${bn(ids.length)}টি নির্বাচিত প্রশ্ন Delete করবেন? এই কাজ পূর্বাবস্থায় ফেরানো যাবে না।`))return;const{error}=await db.from('questions').delete().in('id',ids);if(error)return msg('moveMsg',error.message,true);ids.forEach(id=>selectedIds.delete(id));msg('moveMsg',`✅ ${bn(ids.length)}টি প্রশ্ন Delete হয়েছে`);await loadQuestions()}
async function openMoveQuestions(){const ids=selectedQuestionIds();if(!ids.length)return msg('moveMsg','আগে যে প্রশ্নগুলো Move করতে চান সেগুলো Select করুন',true);const foldersForMove=await db.from('question_bank_folders').select('id,folder_name').eq('sub_category',CATS[cat]).order('id');if(foldersForMove.error)return msg('moveMsg',foldersForMove.error.message,true);$('moveFolder').innerHTML='<option value="">Destination Folder নির্বাচন করুন</option>'+(foldersForMove.data||[]).map(x=>`<option value="${x.id}">${esc(x.folder_name)}</option>`).join('');$('moveSet').innerHTML='<option value="">Destination Set নির্বাচন করুন</option>';$('moveFolder').value='';$('moveModalMsg').textContent=`${bn(ids.length)}টি প্রশ্ন নির্বাচিত`;$('moveModal').classList.remove('hidden')}
async function loadMoveSets(){const id=$('moveFolder').value;if(!id){$('moveSet').innerHTML='<option value="">Destination Set নির্বাচন করুন</option>';return}const{data,error}=await db.from('question_bank_sets').select('id,set_name').eq('folder_id',Number(id)).order('id');if(error)return msg('moveModalMsg',error.message,true);$('moveSet').innerHTML='<option value="">Destination Set নির্বাচন করুন</option>'+(data||[]).map(x=>`<option value="${x.id}">${esc(x.set_name)}</option>`).join('')}
function closeMoveQuestions(){$('moveModal').classList.add('hidden');$('moveModalMsg').textContent=''}
async function moveSelectedQuestions(){const ids=selectedQuestionIds(),folderId=$('moveFolder').value,setId=$('moveSet').value;if(!ids.length)return msg('moveModalMsg','কোনো প্রশ্ন Select করা হয়নি',true);if(!folderId||!setId)return msg('moveModalMsg','Destination Folder এবং Set নির্বাচন করুন',true);if(!confirm(`${bn(ids.length)}টি প্রশ্ন এই Folder/Set-এ Move করবেন?`))return;msg('moveModalMsg','Move হচ্ছে...');const{error}=await db.from('questions').update({folder_id:Number(folderId),set_id:Number(setId),category:CATS[cat]}).in('id',ids);if(error)return msg('moveModalMsg',error.message,true);ids.forEach(id=>selectedIds.delete(id));closeMoveQuestions();msg('moveMsg',`✅ ${bn(ids.length)}টি প্রশ্ন Move হয়েছে`);await loadQuestions()}
async function createExam(){const name=$('examName').value.trim();if(!name)return msg('examMsg','পরীক্ষার নাম দিন',true);const{data,error}=await db.from('exams').insert({exam_name:name,status:$('examStatus').value,total_questions:0,marks_per_question:1,negative_mark:0,pass_mark:0}).select('id').single();if(error)return msg('examMsg',error.message,true);const s=await db.from('exam_settings').upsert({exam_id:data.id,total_questions:0,total_marks:0,pass_mark:0,duration_minutes:20,marks_per_question:1,negative_mark:0,show_answers:false,multiple_attempts:false,device_attempt_protection:true,random_questions:false,random_options:false},{onConflict:'exam_id'});if(s.error)return msg('examMsg',s.error.message,true);$('examName').value='';msg('examMsg','✅ Exam তৈরি হয়েছে');await loadExams();$('examSelect').value=data.id;loadSettings()}
async function loadExams(){const{data,error}=await db.from('exams').select('id,exam_name,status,total_questions,marks_per_question,negative_mark,pass_mark').order('id',{ascending:false});if(error)return msg('examMsg',error.message,true);exams=data||[];$('sExams').textContent=bn(exams.length);$('sActive').textContent=bn(exams.filter(x=>x.status==='active').length);const opt='<option value="">Exam নির্বাচন করুন</option>'+exams.map(x=>`<option value="${x.id}">${esc(x.exam_name)} (#${x.id})</option>`).join('');$('examSelect').innerHTML=opt;$('mapExam').innerHTML=opt;$('exams').innerHTML=exams.map(x=>`<div class="examrow"><b>${esc(x.exam_name)}</b> · ${esc(x.status)} · ${bn(x.total_questions||0)} প্রশ্ন<br><span class="link">${location.origin}${location.pathname.replace(/\/[^/]*$/,'/../')}?exam=${x.id}</span><br><button onclick="copyLink(${x.id})">🔗 Exam Link কপি</button><button class="secondary" onclick="activate(${x.id},'${x.status==='active'?'inactive':'active'}')">${x.status==='active'?'Inactive':'Active'}</button></div>`).join('');const count=await db.from('questions').select('id',{count:'exact',head:true});$('sQuestions').textContent=bn(count.count||0)}
async function copyLink(id){const base=new URL('../index.html',location.href).href+'?exam='+id;try{await navigator.clipboard.writeText(base);alert('Exam Link copied')}catch(_){prompt('Exam Link',base)}}
async function activate(id,status){const{error}=await db.from('exams').update({status}).eq('id',id);if(error)return msg('examMsg',error.message,true);await loadExams()}
async function loadSettings(){const id=$('examSelect').value;if(!id)return;const{data,error}=await db.from('exam_settings').select('*').eq('exam_id',id).maybeSingle();if(error)return msg('settingsMsg',error.message,true);const s=data||{};$('totalQ').value=s.total_questions??0;$('totalMarks').value=s.total_marks??0;$('pass').value=s.pass_mark??0;$('duration').value=s.duration_minutes??20;$('marks').value=s.marks_per_question??1;$('negative').value=s.negative_mark??0;$('examiner').value=s.examiner_name??'';$('syllabus').value=s.syllabus??'';$('showAnswers').checked=!!s.show_answers;$('multiple').checked=!!s.multiple_attempts;$('device').checked=s.device_attempt_protection!==false;$('randomQ').checked=!!s.random_questions;$('randomO').checked=!!s.random_options;$('startDate').value=s.exam_date||'';$('startTime').value=s.start_time||'';$('endDate').value=s.end_date||'';$('endTime').value=s.end_time||''}
async function saveSettings(){const id=$('examSelect').value;if(!id)return msg('settingsMsg','Exam নির্বাচন করুন',true);const payload={exam_id:id,total_questions:Number($('totalQ').value)||0,total_marks:Number($('totalMarks').value)||0,pass_mark:Number($('pass').value)||0,duration_minutes:Number($('duration').value)||20,marks_per_question:Number($('marks').value)||1,negative_mark:Number($('negative').value)||0,examiner_name:$('examiner').value.trim()||null,syllabus:$('syllabus').value.trim()||null,show_answers:$('showAnswers').checked,multiple_attempts:$('multiple').checked,device_attempt_protection:$('device').checked,random_questions:$('randomQ').checked,random_options:$('randomO').checked,exam_date:$('startDate').value||null,start_time:$('startTime').value||null,end_date:$('endDate').value||null,end_time:$('endTime').value||null};const{error}=await db.from('exam_settings').upsert(payload,{onConflict:'exam_id'});if(error)return msg('settingsMsg',error.message,true);const e=await db.from('exams').update({total_questions:payload.total_questions,marks_per_question:payload.marks_per_question,negative_mark:payload.negative_mark,pass_mark:payload.pass_mark}).eq('id',id);if(e.error)return msg('settingsMsg',e.error.message,true);msg('settingsMsg','✅ Exam Settings সংরক্ষিত হয়েছে');await loadExams()}
async function loadPool(){const examId=$('mapExam').value;if(!examId)return msg('mapMsg','Exam নির্বাচন করুন',true);let q=db.from('questions').select('id,question_text,category,folder_id,set_id,question_number').limit(200);if($('mapFolder').value)q=q.eq('folder_id',Number($('mapFolder').value));if($('mapSet').value)q=q.eq('set_id',Number($('mapSet').value));const{data,error}=await q;if(error)return msg('mapMsg',error.message,true);const existing=await db.from('exam_questions').select('question_id').eq('exam_id',examId);const ids=new Set((existing.data||[]).map(x=>String(x.question_id)));$('pool').innerHTML=(data||[]).map(x=>`<label class="q"><input type="checkbox" class="poolq" value="${x.id}" ${ids.has(String(x.id))?'checked':''}> ${esc(x.question_text)} <span class="small">(${esc(x.category||'')})</span></label>`).join('')+`<button onclick="saveMapping(${examId})">Exam-এ নির্বাচিত প্রশ্ন Save করুন</button>`}
async function saveMapping(examId){const ids=[...document.querySelectorAll('.poolq:checked')].map(x=>Number(x.value));const old=await db.from('exam_questions').delete().eq('exam_id',examId);if(old.error)return msg('mapMsg',old.error.message,true);if(ids.length){const{error}=await db.from('exam_questions').insert(ids.map((id,i)=>({exam_id:examId,question_id:id,question_order:i+1})));if(error)return msg('mapMsg',error.message,true)}await db.from('exams').update({total_questions:ids.length}).eq('id',examId);await db.from('exam_settings').update({total_questions:ids.length}).eq('exam_id',examId);msg('mapMsg',`✅ ${bn(ids.length)}টি প্রশ্ন Exam-এ যুক্ত হয়েছে`);await loadExams()}
document.addEventListener('change',e=>{if(e.target.classList?.contains('question-check')){const id=Number(e.target.value);if(e.target.checked)selectedIds.add(id);else selectedIds.delete(id)}});
$('folder').onchange=loadSets;$('filterFolder').onchange=async()=>{await loadFilterSets();await loadQuestions()};$('filterSet').onchange=loadQuestions;$('filterSubject').onchange=loadQuestions;$('search').oninput=loadQuestions;$('mapFolder').onchange=loadMapSets;$('moveFolder').onchange=loadMoveSets;
selectCategory('verification_test');init();
