const $=id=>document.getElementById(id),BN='০১২৩৪৫৬৭৮৯';const bn=n=>String(n??'').replace(/\d/g,d=>BN[d]);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let exams=[],mapExamId=null;
const msg=(t,e=false)=>{$('msg').textContent=t;$('msg').style.color=e?'#b91c1c':'#166534'};const mapMsg=(t,e=false)=>{$('mapMsg').textContent=t;$('mapMsg').style.color=e?'#b91c1c':'#166534'};
async function init(){const{data}=await db.auth.getSession();if(!data.session)return location.href='admin_dashboard_split.html';await loadExams();await loadFolders();const id=new URLSearchParams(location.search).get('exam');if(id)openMapping(Number(id))}
async function loadExams(){const{data,error}=await db.from('exams').select('id,exam_name,status,total_questions,marks_per_question,negative_mark,pass_mark').order('id',{ascending:false});if(error)return msg(error.message,true);exams=data||[];$('exams').innerHTML=exams.length?exams.map(e=>{const link=new URL('index.html?exam='+e.id,location.href).href;return `<div class="exam-card${mapExamId===e.id?' mapping-open':''}" data-exam-id="${e.id}"><div class="exam-head"><div><h2>${esc(e.exam_name)}</h2><div>${e.status==='active'?'🟢 Active':'⚪ Inactive'} · ${bn(e.total_questions||0)}টি প্রশ্ন</div></div><button class="secondary" onclick="toggleStatus(${e.id},'${e.status==='active'?'inactive':'active'}')">${e.status==='active'?'Inactive করুন':'Active করুন'}</button></div><div class="linkbox">${esc(link)}</div><div class="exam-actions"><button onclick="copyLink('${link.replace(/'/g,"\\'")}')">🔗 Link কপি</button><button onclick="location.href='exam-setting.html?exam=${e.id}'">⚙️ সেটিংস</button><button onclick="openMapping(${e.id})">➕/➖ প্রশ্ন</button><button onclick="location.href='question-paper.html?exam=${e.id}'">📝 প্রশ্নপত্র</button><button onclick="location.href='answer-paper.html?exam=${e.id}'">✅ উত্তরপত্র</button><button onclick="location.href='results.html?exam=${e.id}'">📊 ফলাফল</button><button onclick="renameExam(${e.id},'${esc(e.exam_name).replace(/'/g,"\\'")}')">✏️ নাম পরিবর্তন</button><button class="danger" onclick="deleteExam(${e.id},'${esc(e.exam_name).replace(/'/g,"\\'")}')">🗑️ ডিলিট</button></div></div>`}).join(''):'<div class="card">কোনো পরীক্ষা নেই।</div>';if(mapExamId){const card=document.querySelector(`[data-exam-id="${mapExamId}"]`);if(card){card.classList.add('mapping-open');card.appendChild($('mapping'));$('mapping').classList.remove('hidden');$('mapping').classList.add('mapping-inline')}}}

async function copyLink(link){try{await navigator.clipboard.writeText(link);msg('✅ Exam Link কপি হয়েছে')}catch(_){prompt('Exam Link',link)}}
async function toggleStatus(id,status){const{error}=await db.from('exams').update({status}).eq('id',id);if(error)return msg(error.message,true);await loadExams()}
async function renameExam(id,current){const name=prompt('নতুন পরীক্ষার নাম',current);if(name===null)return;if(!name.trim())return alert('পরীক্ষার নাম খালি রাখা যাবে না।');const{error}=await db.from('exams').update({exam_name:name.trim()}).eq('id',id);if(error)return msg(error.message,true);await loadExams()}
async function deleteExam(id,name){if(!confirm(`“${name}” পরীক্ষা ডিলিট করবেন?\n\nQuestion Bank-এর প্রশ্ন ডিলিট হবে না। এই পরীক্ষার mapping/settings/results-এর attempt data মুছে যাবে।`))return;for(const table of ['attempt_answers','exam_attempts','exam_questions','exam_settings']){const r=await db.from(table).delete().eq('exam_id',id);if(r.error)return msg(table+': '+r.error.message,true)}const{error}=await db.from('exams').delete().eq('id',id);if(error)return msg(error.message,true);msg('✅ পরীক্ষা ডিলিট হয়েছে');await loadExams()}
async function loadFolders(){const{data,error}=await db.from('question_bank_folders').select('id,folder_name').order('id');if(error)return mapMsg(error.message,true);$('folder').innerHTML='<option value="">সব Folder</option>'+(data||[]).map(x=>`<option value="${x.id}">${esc(x.folder_name)}</option>`).join('');await loadSets()}
async function loadSets(){const id=$('folder').value;if(!id){$('set').innerHTML='<option value="">সব Set</option>';return}const{data,error}=await db.from('question_bank_sets').select('id,set_name').eq('folder_id',Number(id)).order('id');if(error)return mapMsg(error.message,true);$('set').innerHTML='<option value="">সব Set</option>'+(data||[]).map(x=>`<option value="${x.id}">${esc(x.set_name)}</option>`).join('')}
async function openMapping(id){mapExamId=id;const card=document.querySelector(`[data-exam-id="${id}"]`);if(card){document.querySelectorAll('.exam-card.mapping-open').forEach(x=>x.classList.remove('mapping-open'));card.classList.add('mapping-open');card.appendChild($('mapping'));$('mapping').classList.remove('hidden');$('mapping').classList.add('mapping-inline');card.scrollIntoView({behavior:'smooth',block:'start'})}const e=exams.find(x=>x.id===id);$('mapTitle').textContent='পরীক্ষা: '+(e?.exam_name||id);await loadPool()}
function closeMapping(){const panel=$('mapping');panel.classList.add('hidden');panel.classList.remove('mapping-inline');const card=panel.closest('.exam-card');if(card)card.classList.remove('mapping-open');document.querySelectorAll('.exam-card.mapping-open').forEach(x=>x.classList.remove('mapping-open'));mapExamId=null}

async function loadPool(){if(!mapExamId)return;let q=db.from('questions').select('id,question_text,option_a,option_b,option_c,option_d,category,folder_id,set_id,question_number').order('id').limit(500);if($('folder').value)q=q.eq('folder_id',Number($('folder').value));if($('set').value)q=q.eq('set_id',Number($('set').value));const[{data,error},existing]=await Promise.all([q,db.from('exam_questions').select('question_id').eq('exam_id',mapExamId)]);if(error)return mapMsg(error.message,true);if(existing.error)return mapMsg(existing.error.message,true);const ids=new Set((existing.data||[]).map(x=>String(x.question_id)));$('pool').innerHTML=(data||[]).map(x=>`<div class="q"><div class="qhead"><input type="checkbox" class="poolq" value="${x.id}" ${ids.has(String(x.id))?'checked':''}><div><div class="qtext"><b>${bn(x.question_number||'')}</b> ${esc(x.question_text)}</div><div class="opts">ক. ${esc(x.option_a)}<br>খ. ${esc(x.option_b)}<br>গ. ${esc(x.option_c)}<br>ঘ. ${esc(x.option_d)}</div><div class="meta">${esc(x.category||'')}</div></div></div></div>`).join('')||'কোনো প্রশ্ন পাওয়া যায়নি।';$('selectAll').checked=(data||[]).length>0&&(data||[]).every(x=>ids.has(String(x.id)));mapMsg(`${bn((data||[]).length)}টি প্রশ্ন দেখানো হয়েছে।`)}
async function saveMapping(){if(!mapExamId)return;const visible=[...document.querySelectorAll('.poolq')].map(x=>Number(x.value));const checked=new Set([...document.querySelectorAll('.poolq:checked')].map(x=>Number(x.value)));const old=await db.from('exam_questions').select('question_id').eq('exam_id',mapExamId);if(old.error)return mapMsg(old.error.message,true);const keep=(old.data||[]).map(x=>Number(x.question_id)).filter(id=>!visible.includes(id));const finalIds=[...keep,...checked];const del=await db.from('exam_questions').delete().eq('exam_id',mapExamId);if(del.error)return mapMsg(del.error.message,true);if(finalIds.length){const{error}=await db.from('exam_questions').insert(finalIds.map((id,i)=>({exam_id:mapExamId,question_id:id,question_order:i+1})));if(error)return mapMsg(error.message,true)}await db.from('exams').update({total_questions:finalIds.length}).eq('id',mapExamId);await db.from('exam_settings').update({total_questions:finalIds.length}).eq('exam_id',mapExamId);mapMsg(`✅ ${bn(finalIds.length)}টি প্রশ্ন সংরক্ষিত হয়েছে`);await loadExams();await loadPool()}
$('folder').addEventListener('change',async()=>{await loadSets();await loadPool()});$('set').addEventListener('change',loadPool);$('loadPool').onclick=loadPool;$('selectAll').addEventListener('change',e=>document.querySelectorAll('.poolq').forEach(x=>x.checked=e.target.checked));$('deselectAll').onclick=()=>{document.querySelectorAll('.poolq').forEach(x=>x.checked=false);$('selectAll').checked=false};$('pool').addEventListener('change',e=>{if(e.target.classList.contains('poolq')){const a=[...document.querySelectorAll('.poolq')];$('selectAll').checked=a.length>0&&a.every(x=>x.checked)}});$('saveMap').onclick=saveMapping;init();
