const CATS={recruitment:'নিয়োগ পরীক্ষা',verification_test:'যাচাই পরীক্ষা',recent:'সাম্প্রতিক প্রশ্ন'};
let cat='verification_test',subjects=[],folders=[],sets=[],importData=[];
const $=id=>document.getElementById(id);
const bn=n=>String(n??'').replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[d]);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function msg(t,err=false){$('msg').textContent=t;$('msg').style.color=err?'#b91c1c':'#166534'}
function setCat(c){cat=c;document.querySelectorAll('.cat').forEach(x=>x.classList.toggle('active',x.dataset.cat===c));$('currentCat').textContent='বর্তমান Category: '+CATS[c];loadFolders()}
async function loadSubjects(){const{data,error}=await db.from('subjects').select('id,name').order('id');if(error)return msg('Subject লোড হয়নি: '+error.message,true);subjects=data||[];$('subject').innerHTML='<option value="">বিষয় নির্বাচন করুন</option>'+subjects.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
async function loadFolders(){const{data,error}=await db.from('question_bank_folders').select('id,folder_name').eq('sub_category',CATS[cat]).order('id');if(error)return msg(error.message,true);folders=data||[];$('folder').innerHTML='<option value="">Folder নির্বাচন করুন</option>'+folders.map(x=>`<option value="${x.id}">${esc(x.folder_name)}</option>`).join('');$('newFolder').value='';await loadSets()}
async function loadSets(){const id=$('folder').value;if(!id){$('set').innerHTML='<option value="">Set নির্বাচন করুন</option>';return}const{data,error}=await db.from('question_bank_sets').select('id,set_name').eq('folder_id',Number(id)).order('id');if(error)return msg(error.message,true);sets=data||[];$('set').innerHTML='<option value="">Set নির্বাচন করুন</option>'+sets.map(x=>`<option value="${x.id}">${esc(x.set_name)}</option>`).join('')}
async function createFolder(){const name=$('newFolder').value.trim();if(!name)return msg('Folder-এর নাম দিন',true);const{data,error}=await db.from('question_bank_folders').insert({sub_category:CATS[cat],folder_name:name}).select('id').single();if(error)return msg(error.message,true);$('newFolder').value='';await loadFolders();$('folder').value=data.id;await loadSets();msg('✅ Folder তৈরি হয়েছে')}
async function createSet(){const fid=$('folder').value,name=$('newSet').value.trim();if(!fid)return msg('আগে Folder নির্বাচন করুন',true);if(!name)return msg('Set-এর নাম দিন',true);const{data,error}=await db.from('question_bank_sets').insert({folder_id:Number(fid),set_name:name}).select('id').single();if(error)return msg(error.message,true);$('newSet').value='';await loadSets();$('set').value=data.id;msg('✅ Set তৈরি হয়েছে')}
async function addManual(){const fid=$('folder').value,sid=$('set').value,sub=$('subject').value,text=$('qtext').value.trim(),a=$('a').value.trim(),b=$('b').value.trim(),c=$('c').value.trim(),d=$('d').value.trim(),correct=$('correct').value;if(!fid||!sid||!sub||!text||!a||!b||!c||!d||!correct)return msg('Category, Folder, Set, বিষয়, প্রশ্ন, চার অপশন ও সঠিক উত্তর পূরণ করুন',true);const p={folder_id:Number(fid),set_id:Number(sid),subject_id:Number(sub),category:CATS[cat],source_type:cat,question_number:$('qno').value?Number($('qno').value):null,question_text:text,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:correct,explanation:$('explanation').value.trim()||null};const{error}=await db.from('questions').insert(p);if(error)return msg(error.message,true);['qno','qtext','a','b','c','d','explanation'].forEach(id=>$(id).value='');$('correct').value='';msg('✅ প্রশ্ন Question Bank-এ যোগ হয়েছে')}
function template(){const rows=[['category','folder','set','subject','question_number','question','option_a','option_b','option_c','option_d','correct_answer','explanation','source'],['যাচাই পরীক্ষা','ব্রেইন বুস্টার মডেল টেস্ট','মডেল টেস্ট ৩','বাংলাদেশ',1,'বাংলাদেশের রাজধানী কোনটি?','ঢাকা','চট্টগ্রাম','রাজশাহী','খুলনা','A','','']];const ws=XLSX.utils.aoa_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Questions');XLSX.writeFile(wb,'question-import-template.xlsx')}
function norm(v){return String(v??'').trim().toLowerCase()}
async function previewImport(){const f=$('file').files[0];if(!f)return msg('CSV/Excel নির্বাচন করুন',true);const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});importData=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});$('preview').innerHTML=`<b>${bn(importData.length)}টি row</b><pre>${esc(JSON.stringify(importData.slice(0,5),null,2))}</pre>`;$('importBtn').classList.remove('hidden');msg('Preview প্রস্তুত')}
async function importRows(){let ok=0,fail=[];for(let i=0;i<importData.length;i++){const r=importData[i],category=Object.values(CATS).includes(String(r.category).trim())?String(r.category).trim():CATS[cat],folderName=String(r.folder||'').trim(),setName=String(r.set||'').trim();if(!r.question||!r.option_a||!r.option_b||!r.option_c||!r.option_d||!r.correct_answer){fail.push(`Row ${i+2}: question/options/correct_answer missing`);continue}let fid=null,sid=null;if(folderName){let fr=await db.from('question_bank_folders').select('id').eq('sub_category',category).eq('folder_name',folderName).maybeSingle();if(fr.error){fail.push(`Row ${i+2}: ${fr.error.message}`);continue}fid=fr.data?.id;if(!fid){const x=await db.from('question_bank_folders').insert({sub_category:category,folder_name:folderName}).select('id').single();if(x.error){fail.push(`Row ${i+2}: ${x.error.message}`);continue}fid=x.data.id}}else{fid=Number($('folder').value)||null}if(setName&&fid){let sr=await db.from('question_bank_sets').select('id').eq('folder_id',fid).eq('set_name',setName).maybeSingle();if(sr.error){fail.push(`Row ${i+2}: ${sr.error.message}`);continue}sid=sr.data?.id;if(!sid){const x=await db.from('question_bank_sets').insert({folder_id:fid,set_name:setName}).select('id').single();if(x.error){fail.push(`Row ${i+2}: ${x.error.message}`);continue}sid=x.data.id}}else sid=Number($('set').value)||null;if(!fid||!sid){fail.push(`Row ${i+2}: Folder/Set দিন অথবা আগে নির্বাচন করুন`);continue}let sub=null;if(r.subject){sub=subjects.find(x=>norm(x.name)===norm(r.subject));if(!sub){fail.push(`Row ${i+2}: Subject পাওয়া যায়নি: ${r.subject}`);continue}}const p={folder_id:fid,set_id:sid,subject_id:sub?.id||null,category,source_type:cat,source_name:String(r.source||'').trim()||null,question_number:r.question_number?Number(r.question_number):null,question_text:String(r.question).trim(),option_a:String(r.option_a).trim(),option_b:String(r.option_b).trim(),option_c:String(r.option_c).trim(),option_d:String(r.option_d).trim(),correct_answer:String(r.correct_answer).trim().toUpperCase(),explanation:String(r.explanation||'').trim()||null};const x=await db.from('questions').insert(p);if(x.error)fail.push(`Row ${i+2}: ${x.error.message}`);else ok++}msg(`✅ ${bn(ok)}টি Import হয়েছে${fail.length?` | ❌ ${bn(fail.length)}টি ব্যর্থ`:''}`,!!fail.length);if(fail.length)$('preview').innerHTML+=`<div class="error">${fail.map(esc).join('<br>')}</div>`}
async function init(){const{data,error}=await db.auth.getSession();if(error)return msg(error.message,true);if(!data.session){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadSubjects();setCat('verification_test')}
window.addEventListener('load',init)
