const CATS={recruitment:'নিয়োগ পরীক্ষা',verification_test:'যাচাই পরীক্ষা',recent:'সাম্প্রতিক প্রশ্ন'};let cat='verification_test',folders=[],sets=[],subjects=[],importData=[];
const $=id=>document.getElementById(id),bn=n=>String(n??'').replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[d]),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function msg(id,t,err=false){const e=$(id);if(!e)return;e.textContent=t;e.style.color=err?'#b91c1c':'#166534'}
async function login(){msg('loginMsg','Login হচ্ছে...');const{error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return msg('loginMsg',error.message,true);await init()}
async function logout(){await db.auth.signOut();location.reload()}
async function init(){const{data,error}=await db.auth.getSession();if(error)return msg('loginMsg',error.message,true);if(!data.session)return; $('login').classList.add('hidden');$('app').classList.remove('hidden');await loadSubjects();await selectCategory(cat)}
async function loadSubjects(){const{data,error}=await db.from('subjects').select('id,name').order('id');if(error)return msg('qmsg',error.message,true);subjects=data||[];$('subject').innerHTML='<option value="">বিষয় নির্বাচন করুন</option>'+subjects.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
async function selectCategory(c){cat=c;document.querySelectorAll('.cats button').forEach(b=>b.classList.remove('active'));$('cat-'+c)?.classList.add('active');$('currentCat').textContent='বর্তমান Category: '+CATS[c];await loadFolders()}
async function loadFolders(){const{data,error}=await db.from('question_bank_folders').select('id,folder_name').eq('sub_category',CATS[cat]).order('id');if(error)return msg('folderMsg',error.message,true);folders=data||[];$('folder').innerHTML='<option value="">Folder নির্বাচন করুন</option>'+folders.map(x=>`<option value="${x.id}">${esc(x.folder_name)}</option>`).join('');await loadSets()}
async function loadSets(){const id=$('folder').value;if(!id){sets=[];$('set').innerHTML='<option value="">Set নির্বাচন করুন</option>';return}const{data,error}=await db.from('question_bank_sets').select('id,set_name').eq('folder_id',Number(id)).order('id');if(error)return msg('folderMsg',error.message,true);sets=data||[];$('set').innerHTML='<option value="">Set নির্বাচন করুন</option>'+sets.map(x=>`<option value="${x.id}">${esc(x.set_name)}</option>`).join('')}
async function createFolder(){const name=$('newFolder').value.trim();if(!name)return msg('folderMsg','Folder-এর নাম দিন',true);const{data,error}=await db.from('question_bank_folders').insert({sub_category:CATS[cat],folder_name:name}).select('id').single();if(error)return msg('folderMsg',error.message,true);$('newFolder').value='';await loadFolders();$('folder').value=String(data.id);await loadSets();msg('folderMsg','✅ Folder তৈরি হয়েছে')}
async function createSet(){const folderId=$('folder').value,name=$('newSet').value.trim();if(!folderId)return msg('folderMsg','আগে Folder নির্বাচন করুন',true);if(!name)return msg('folderMsg','Set-এর নাম দিন',true);const{data,error}=await db.from('question_bank_sets').insert({folder_id:Number(folderId),set_name:name}).select('id').single();if(error)return msg('folderMsg',error.message,true);$('newSet').value='';await loadSets();$('set').value=String(data.id);msg('folderMsg','✅ Set তৈরি হয়েছে')}
async function addManual(){const folderId=$('folder').value,setId=$('set').value,subjectId=$('subject').value,text=$('qtext').value.trim(),a=$('a').value.trim(),b=$('b').value.trim(),c=$('c').value.trim(),d=$('d').value.trim(),correct=$('correct').value;if(!folderId||!setId)return msg('qmsg','Category, Folder ও Set নির্বাচন করুন',true);if(!subjectId||!text||!a||!b||!c||!d||!correct)return msg('qmsg','বিষয়, প্রশ্ন, চার অপশন ও সঠিক উত্তর পূরণ করুন',true);const p={folder_id:Number(folderId),set_id:Number(setId),subject_id:Number(subjectId),question_text:text,option_a:a,option_b:b,option_c:c,option_d:d,correct_answer:correct,explanation:$('explanation').value.trim()||null,question_number:$('qno').value?Number($('qno').value):null,category:CATS[cat],source_type:cat};const{error}=await db.from('questions').insert(p);if(error)return msg('qmsg',error.message,true);['qno','qtext','a','b','c','d','explanation'].forEach(x=>$(x).value='');$('correct').value='';msg('qmsg','✅ প্রশ্ন Question Bank-এ যোগ হয়েছে')}
function template(){const rows=[['question','source','option_a','option_b','option_c','option_d','correct_answer','question_number','subject','explanation','category','folder','set'],['বাংলাদেশের রাজধানী কোনটি?','বিসিএস','ঢাকা','চট্টগ্রাম','রাজশাহী','খুলনা','A',1,'বাংলাদেশ','','যাচাই পরীক্ষা','','']];const ws=XLSX.utils.aoa_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Questions');XLSX.writeFile(wb,'question-import-template.xlsx')}
async function previewImport(){const f=$('file').files[0];if(!f)return msg('qmsg','CSV/Excel file নির্বাচন করুন',true);const data=XLSX.read(await f.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(data.Sheets[data.SheetNames[0]],{defval:''});importData=rows;$('preview').innerHTML=`<div class="q"><b>${bn(rows.length)}টি row পাওয়া গেছে</b><pre>${esc(JSON.stringify(rows.slice(0,5),null,2))}</pre></div>`;$('importBtn').classList.remove('hidden');msg('qmsg','Preview প্রস্তুত হয়েছে')}
function norm(v){return String(v??'').trim().toLowerCase()}
async function importRows(){let ok=0,fail=[];for(let i=0;i<importData.length;i++){const r=importData[i],category=Object.values(CATS).includes(String(r.category).trim())?String(r.category).trim():CATS[cat],folderName=String(r.folder||'').trim(),setName=String(r.set||'').trim();if(!folderName||!setName||!r.question||!r.source||!r.option_a||!r.option_b||!r.option_c||!r.option_d||!r.correct_answer){fail.push(`Row ${i+2}: required field missing`);continue}let fr=await db.from('question_bank_folders').select('id').eq('sub_category',category).eq('folder_name',folderName).maybeSingle();if(fr.error){fail.push(`Row ${i+2}: ${fr.error.message}`);continue}let fid=fr.data?.id;if(!fid){const x=await db.from('question_bank_folders').insert({sub_category:category,folder_name:folderName}).select('id').single();if(x.error){fail.push(`Row ${i+2}: ${x.error.message}`);continue}fid=x.data.id}let sr=await db.from('question_bank_sets').select('id').eq('folder_id',fid).eq('set_name',setName).maybeSingle();if(sr.error){fail.push(`Row ${i+2}: ${sr.error.message}`);continue}let sid=sr.data?.id;if(!sid){const x=await db.from('question_bank_sets').insert({folder_id:fid,set_name:setName}).select('id').single();if(x.error){fail.push(`Row ${i+2}: ${x.error.message}`);continue}sid=x.data.id}let sub=null;if(r.subject){sub=subjects.find(x=>norm(x.name)===norm(r.subject));if(!sub){fail.push(`Row ${i+2}: Subject পাওয়া যায়নি: ${r.subject}`);continue}}const p={folder_id:fid,set_id:sid,subject_id:sub?.id||null,category,source_name:String(r.source).trim(),source_type:category,question_number:r.question_number?Number(r.question_number):null,question_text:String(r.question).trim(),option_a:String(r.option_a).trim(),option_b:String(r.option_b).trim(),option_c:String(r.option_c).trim(),option_d:String(r.option_d).trim(),correct_answer:String(r.correct_answer).trim().toUpperCase(),explanation:String(r.explanation||'').trim()||null};const x=await db.from('questions').insert(p);if(x.error)fail.push(`Row ${i+2}: ${x.error.message}`);else ok++}msg('qmsg',`✅ ${bn(ok)}টি Import হয়েছে${fail.length?` | ❌ ${bn(fail.length)}টি ব্যর্থ`:''}`,!!fail.length);if(fail.length)$('preview').innerHTML+='<div class="q">'+fail.map(esc).join('<br>')+'</div>'}
async function renameSelectedFolder(){const id=$('folder').value;if(!id)return msg('folderMsg','আগে Folder নির্বাচন করুন',true);const old=$('folder').selectedOptions[0]?.textContent||'';const name=prompt('নতুন Folder-এর নাম লিখুন:',old);if(name===null)return;const value=name.trim();if(!value)return msg('folderMsg','Folder-এর নাম খালি রাখা যাবে না',true);const{error}=await db.from('question_bank_folders').update({folder_name:value}).eq('id',Number(id));if(error)return msg('folderMsg',error.message,true);await loadFolders();$('folder').value=String(id);await loadSets();msg('folderMsg','✅ Folder-এর নাম পরিবর্তন হয়েছে')}
async function deleteSelectedFolder(){const id=$('folder').value;if(!id)return msg('folderMsg','আগে Folder নির্বাচন করুন',true);const name=$('folder').selectedOptions[0]?.textContent||'এই Folder';const check=await db.from('question_bank_sets').select('id',{count:'exact',head:true}).eq('folder_id',Number(id));if(check.error)return msg('folderMsg',check.error.message,true);if(check.count&&!confirm(`"${name}" Folder-এর ভিতরে ${check.count}টি Set আছে। Delete করবেন?`))return;const{error}=await db.from('question_bank_folders').delete().eq('id',Number(id));if(error)return msg('folderMsg',error.message,true);await loadFolders();msg('folderMsg','✅ Folder Delete হয়েছে')}
async function renameSelectedSet(){const id=$('set').value;if(!id)return msg('folderMsg','আগে Set নির্বাচন করুন',true);const old=$('set').selectedOptions[0]?.textContent||'';const name=prompt('নতুন Set-এর নাম লিখুন:',old);if(name===null)return;const value=name.trim();if(!value)return msg('folderMsg','Set-এর নাম খালি রাখা যাবে না',true);const{error}=await db.from('question_bank_sets').update({set_name:value}).eq('id',Number(id));if(error)return msg('folderMsg',error.message,true);await loadSets();$('set').value=String(id);msg('folderMsg','✅ Set-এর নাম পরিবর্তন হয়েছে')}
async function deleteSelectedSet(){const id=$('set').value;if(!id)return msg('folderMsg','আগে Set নির্বাচন করুন',true);const name=$('set').selectedOptions[0]?.textContent||'এই Set';const check=await db.from('questions').select('id',{count:'exact',head:true}).eq('set_id',Number(id));if(check.error)return msg('folderMsg',check.error.message,true);if(check.count&&!confirm(`"${name}" Set-এর মধ্যে ${check.count}টি প্রশ্ন আছে। Delete করলে প্রশ্নগুলোও মুছে যাবে। নিশ্চিত?`))return;const{error}=await db.from('question_bank_sets').delete().eq('id',Number(id));if(error)return msg('folderMsg',error.message,true);await loadSets();msg('folderMsg','✅ Set Delete হয়েছে')}
$('folder').addEventListener('change',loadSets);init();
