const CATS={recruitment:'নিয়োগ পরীক্ষা',verification_test:'যাচাই পরীক্ষা',recent:'সাম্প্রতিক প্রশ্ন'};let cat='verification_test',subjects=[];
const $=id=>document.getElementById(id),bn=n=>String(n??'').replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[d]),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function msg(id,t,err=false){const e=$(id);if(!e)return;e.textContent=t;e.style.color=err?'#b91c1c':'#166534'}
async function login(){msg('loginMsg','Login হচ্ছে...');const{error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return msg('loginMsg',error.message,true);await init()}
async function logout(){await db.auth.signOut();location.reload()}
async function init(){const{data,error}=await db.auth.getSession();if(error)return msg('loginMsg',error.message,true);if(!data.session)return;$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadSubjects();await selectCategory(cat)}
async function loadSubjects(){const{data,error}=await db.from('subjects').select('id,name').order('id');if(error)return msg('loginMsg',error.message,true);subjects=data||[];$('filterSubject').innerHTML='<option value="">সব বিষয়</option>'+(subjects||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
async function selectCategory(c){cat=c;document.querySelectorAll('.cats button').forEach(b=>b.classList.remove('active'));$('cat-'+c)?.classList.add('active');$('currentCat').textContent='বর্তমান Category: '+CATS[c];await loadFilterFolders();await loadQuestions()}
async function loadFilterFolders(){const{data,error}=await db.from('question_bank_folders').select('id,folder_name').eq('sub_category',CATS[cat]).order('id');if(error)return msg('loginMsg',error.message,true);$('filterFolder').innerHTML='<option value="">সব Folder</option>'+(data||[]).map(x=>`<option value="${x.id}">${esc(x.folder_name)}</option>`).join('');await loadFilterSets()}
async function loadFilterSets(){const id=$('filterFolder').value;if(!id){$('filterSet').innerHTML='<option value="">সব Set</option>';return}const{data,error}=await db.from('question_bank_sets').select('id,set_name').eq('folder_id',Number(id)).order('id');if(error)return msg('loginMsg',error.message,true);$('filterSet').innerHTML='<option value="">সব Set</option>'+(data||[]).map(x=>`<option value="${x.id}">${esc(x.set_name)}</option>`).join('')}
function sourceText(x){return `Source: ${x.category||''} → ${x.folder_name||''} → ${x.set_name||''} → প্রশ্ন নং ${x.question_number??''}`}
async function loadQuestions(){let q=db.from('questions').select('id,question_text,option_a,option_b,option_c,option_d,correct_answer,explanation,question_number,category,folder_id,set_id,subjects(name),question_bank_folders(folder_name),question_bank_sets(set_name)').order('id',{ascending:false}).limit(500);if($('filterFolder').value)q=q.eq('folder_id',Number($('filterFolder').value));if($('filterSet').value)q=q.eq('set_id',Number($('filterSet').value));if($('filterSubject').value)q=q.eq('subject_id',Number($('filterSubject').value));const term=$('search').value.trim();if(term)q=q.ilike('question_text','%'+term+'%');const{data,error}=await q;if(error)return msg('loginMsg',error.message,true);const rows=data||[];$('questions').innerHTML=rows.map((x,i)=>{const correct={A:'ক',B:'খ',C:'গ',D:'ঘ'}[x.correct_answer]||x.correct_answer;return `<div class="q"><b>${bn(i+1)}. ${esc(x.question_text)}</b><div>ক. ${esc(x.option_a)}<br>খ. ${esc(x.option_b)}<br>গ. ${esc(x.option_c)}<br>ঘ. ${esc(x.option_d)}</div><div class="small">সঠিক উত্তর: ${esc(correct)}</div><div class="small">${esc(sourceText({...x,folder_name:x.question_bank_folders?.folder_name,set_name:x.question_bank_sets?.set_name}))}</div>${x.subjects?.name?`<div class="small">বিষয়: ${esc(x.subjects.name)}</div>`:''}${x.explanation?`<div class="small">ব্যাখ্যা: ${esc(x.explanation)}</div>`:''}</div>`}).join('')||'কোনো প্রশ্ন নেই'}
$('filterFolder').addEventListener('change',async()=>{await loadFilterSets();await loadQuestions()});$('filterSet').addEventListener('change',loadQuestions);$('filterSubject').addEventListener('change',loadQuestions);let timer;function searchNow(){clearTimeout(timer);timer=setTimeout(loadQuestions,250)}$('search').addEventListener('input',searchNow);init();
