let subjects=[],folders=[],sets=[],allQuestions=[];
const $=id=>document.getElementById(id),bn=n=>String(n??'').replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[d]),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function msg(t,err=false){$('msg').textContent=t;$('msg').style.color=err?'#b91c1c':'#166534'}
async function loadSubjects(){const{data,error}=await db.from('subjects').select('id,name').order('id');if(error)return msg(error.message,true);subjects=data||[];$('subject').innerHTML='<option value="">সব বিষয়</option>'+subjects.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
async function loadFolders(){const{data,error}=await db.from('question_bank_folders').select('id,folder_name,sub_category').order('id');if(error)return msg(error.message,true);folders=data||[];$('folder').innerHTML='<option value="">সব Folder</option>'+folders.map(x=>`<option value="${x.id}">${esc(x.folder_name)} — ${esc(x.sub_category)}</option>`).join('');await loadSets()}
async function loadSets(){const fid=$('folder').value;if(!fid){$('set').innerHTML='<option value="">সব Set</option>';return}const{data,error}=await db.from('question_bank_sets').select('id,set_name').eq('folder_id',Number(fid)).order('id');if(error)return msg(error.message,true);sets=data||[];$('set').innerHTML='<option value="">সব Set</option>'+sets.map(x=>`<option value="${x.id}">${esc(x.set_name)}</option>`).join('')}
function sourceText(x){return [x.categories?.name||x.category,x.folder?.folder_name,x.set?.set_name,`প্রশ্ন নং ${x.question_number||''}`].filter(Boolean).join(' → ')}
function copyText(x,n){const L={A:'ক',B:'খ',C:'গ',D:'ঘ'};return `${bn(n)}. ${x.question_text}\nক. ${x.option_a}\nখ. ${x.option_b}\nগ. ${x.option_c}\nঘ. ${x.option_d}\nসঠিক উত্তর: ${L[x.correct_answer]||x.correct_answer}`}
async function copyQuestion(id){const x=allQuestions.find(q=>q.id===id);if(!x)return;const n=Number(x._displayNo||0);const t=copyText(x,n);try{await navigator.clipboard.writeText(t);msg('✅ প্রশ্ন কপি হয়েছে')}catch(e){const ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();msg('✅ প্রশ্ন কপি হয়েছে')}}
function render(){const term=$('search').value.trim().toLowerCase(),fid=$('folder').value,sid=$('set').value,sub=$('subject').value;let rows=allQuestions.filter(x=>(!fid||String(x.folder_id)===fid)&&(!sid||String(x.set_id)===sid)&&(!sub||String(x.subject_id)===sub)&&(!term||String(x.question_text).toLowerCase().includes(term)));rows.forEach((x,i)=>x._displayNo=i+1);$('count').textContent=`${bn(rows.length)}টি প্রশ্ন`;$('questions').innerHTML=rows.map(x=>{const L={A:'ক',B:'খ',C:'গ',D:'ঘ'};return `<article class="q" id="q-${x.id}"><div class="qtop"><b>${bn(x._displayNo)}. ${esc(x.question_text)}</b><button class="copy" onclick="copyQuestion(${x.id})">📋 Copy</button></div><div class="opts">ক. ${esc(x.option_a)}<br>খ. ${esc(x.option_b)}<br>গ. ${esc(x.option_c)}<br>ঘ. ${esc(x.option_d)}</div><div class="correct">সঠিক উত্তর: ${L[x.correct_answer]||esc(x.correct_answer)}</div><a class="source" href="question_bank.html?question_id=${x.id}">Source: ${esc(sourceText(x))}</a><div class="subject">বিষয়: ${esc(x.subjects?.name||'')}</div><div class="actions"><button onclick="editQuestion(${x.id})">✏️ Edit</button><button class="danger" onclick="deleteQuestion(${x.id})">🗑️ Delete</button></div></article>`}).join('')||'<div class="empty">কোনো প্রশ্ন পাওয়া যায়নি।</div>';const target=new URLSearchParams(location.search).get('question_id');if(target){setTimeout(()=>document.getElementById('q-'+target)?.scrollIntoView({behavior:'smooth',block:'center'}),150)}}
async function loadQuestions(){let q=db.from('questions').select('id,question_text,option_a,option_b,option_c,option_d,correct_answer,question_number,category,folder_id,set_id,subject_id,source_name,explanation,subjects(name),question_bank_folders(folder_name,sub_category),question_bank_sets(set_name)');const{data,error}=await q.order('id',{ascending:false}).limit(1000);if(error)return msg(error.message,true);allQuestions=(data||[]).map(x=>({...x,folder:x.question_bank_folders,set:x.question_bank_sets,categories:{name:x.category}}));render()}
function openEdit(id){const x=allQuestions.find(q=>q.id===id);if(!x)return;const L=x.correct_answer;$('editId').value=id;$('editQno').value=x.question_number||'';$('editQuestion').value=x.question_text;$('editA').value=x.option_a;$('editB').value=x.option_b;$('editC').value=x.option_c;$('editD').value=x.option_d;$('editCorrect').value=L;$('editExplanation').value=x.explanation||'';$('editModal').classList.remove('hidden')}
window.editQuestion=openEdit;
async function saveEdit(){const id=Number($('editId').value);const p={question_number:$('editQno').value?Number($('editQno').value):null,question_text:$('editQuestion').value.trim(),option_a:$('editA').value.trim(),option_b:$('editB').value.trim(),option_c:$('editC').value.trim(),option_d:$('editD').value.trim(),correct_answer:$('editCorrect').value,explanation:$('editExplanation').value.trim()||null};if(!p.question_text||!p.option_a||!p.option_b||!p.option_c||!p.option_d||!p.correct_answer)return msg('সব প্রয়োজনীয় ঘর পূরণ করুন',true);const{error}=await db.from('questions').update(p).eq('id',id);if(error)return msg(error.message,true);$('editModal').classList.add('hidden');msg('✅ পরিবর্তন সংরক্ষিত হয়েছে');await loadQuestions()}
async function deleteQuestion(id){if(!confirm('এই প্রশ্নটি মুছে ফেলবেন?'))return;const{error}=await db.from('questions').delete().eq('id',id);if(error)return msg(error.message,true);msg('✅ প্রশ্ন মুছে ফেলা হয়েছে');await loadQuestions()}
async function init(){const{data,error}=await db.auth.getSession();if(error)return msg(error.message,true);if(!data.session){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadSubjects();await loadFolders();await loadQuestions()}
$('folder').onchange=async()=>{await loadSets();render()};$('set').onchange=render;$('subject').onchange=render;$('search').oninput=render;window.saveEdit=saveEdit;window.deleteQuestion=deleteQuestion;window.copyQuestion=copyQuestion;window.addEventListener('load',init)
