-- ফেইসবুক পাঠশালা Exam System
-- Master Question Bank + Exam Selection structure
-- এই SQL additive/idempotent। পুরোনো Question/Exam data মুছে দেয় না।

create extension if not exists pgcrypto;

-- ============================================================
-- ১) Question Bank: Category -> Folder -> Set -> Question
-- ============================================================
create table if not exists public.question_bank_folders (
  id bigint generated by default as identity primary key,
  sub_category text not null,
  folder_name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists question_bank_folders_unique
  on public.question_bank_folders(sub_category, folder_name);

create table if not exists public.question_bank_sets (
  id bigint generated by default as identity primary key,
  folder_id bigint not null references public.question_bank_folders(id) on delete cascade,
  set_name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists question_bank_sets_unique
  on public.question_bank_sets(folder_id, set_name);

alter table public.questions
  add column if not exists folder_id bigint references public.question_bank_folders(id) on delete set null,
  add column if not exists set_id bigint references public.question_bank_sets(id) on delete set null,
  add column if not exists question_number integer;

create index if not exists questions_folder_idx on public.questions(folder_id);
create index if not exists questions_set_idx on public.questions(set_id);
create index if not exists questions_subject_idx on public.questions(subject_id);

-- Existing source_name values remain untouched. New Question Bank questions
-- should use folder_id/set_id as the authoritative location.

-- ============================================================
-- ২) Exam -> Master Question mapping
-- ============================================================
create table if not exists public.exam_questions (
  exam_id bigint not null references public.exams(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  question_order integer not null default 1,
  primary key (exam_id, question_id)
);

create index if not exists exam_questions_exam_order_idx
  on public.exam_questions(exam_id, question_order);
create index if not exists exam_questions_question_idx
  on public.exam_questions(question_id);

-- ============================================================
-- ৩) Exam settings
-- ============================================================
create table if not exists public.exam_settings (
  exam_id bigint primary key references public.exams(id) on delete cascade,
  total_questions integer not null default 0 check(total_questions >= 0),
  total_marks numeric(10,2) not null default 0 check(total_marks >= 0),
  pass_mark numeric(10,2) not null default 0 check(pass_mark >= 0),
  duration_minutes integer not null default 20 check(duration_minutes > 0),
  marks_per_question numeric(10,2) not null default 1 check(marks_per_question >= 0),
  negative_mark numeric(10,2) not null default 0 check(negative_mark >= 0),
  exam_date date,
  start_time time,
  end_date date,
  end_time time,
  examiner_name text,
  facebook_page_url text,
  facebook_group_url text,
  show_answers boolean not null default false,
  random_questions boolean not null default false,
  random_options boolean not null default false,
  multiple_attempts boolean not null default false,
  device_attempt_protection boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Existing exam_settings tables get any missing columns.
alter table public.exam_settings
  add column if not exists end_date date,
  add column if not exists examiner_name text,
  add column if not exists facebook_page_url text,
  add column if not exists facebook_group_url text,
  add column if not exists show_answers boolean not null default false,
  add column if not exists random_questions boolean not null default false,
  add column if not exists random_options boolean not null default false,
  add column if not exists multiple_attempts boolean not null default false,
  add column if not exists device_attempt_protection boolean not null default true;

-- ============================================================
-- ৪) Admin access for Folder/Set/Question/Exam mapping
-- ============================================================
alter table public.question_bank_folders enable row level security;
alter table public.question_bank_sets enable row level security;
alter table public.questions enable row level security;
alter table public.exam_questions enable row level security;
alter table public.exam_settings enable row level security;

drop policy if exists question_bank_folders_admin_all on public.question_bank_folders;
create policy question_bank_folders_admin_all
on public.question_bank_folders for all to authenticated
using (true) with check (true);

drop policy if exists question_bank_sets_admin_all on public.question_bank_sets;
create policy question_bank_sets_admin_all
on public.question_bank_sets for all to authenticated
using (true) with check (true);

drop policy if exists questions_admin_all on public.questions;
create policy questions_admin_all
on public.questions for all to authenticated
using (true) with check (true);

drop policy if exists exam_questions_admin_all on public.exam_questions;
create policy exam_questions_admin_all
on public.exam_questions for all to authenticated
using (true) with check (true);

drop policy if exists exam_settings_admin_all on public.exam_settings;
create policy exam_settings_admin_all
on public.exam_settings for all to authenticated
using (true) with check (true);

-- ============================================================
-- ৫) Folder / Set helper RPCs
-- ============================================================
drop function if exists public.create_question_bank_folder(text,text);
create or replace function public.create_question_bank_folder(
  p_sub_category text,
  p_folder_name text
)
returns public.question_bank_folders
language plpgsql security definer set search_path=public
as $$
declare r public.question_bank_folders;
begin
  if auth.uid() is null then raise exception 'Admin login required'; end if;
  insert into public.question_bank_folders(sub_category,folder_name)
  values(trim(p_sub_category),trim(p_folder_name))
  on conflict(sub_category,folder_name) do update set folder_name=excluded.folder_name
  returning * into r;
  return r;
end;
$$;

drop function if exists public.create_question_bank_set(bigint,text);
create or replace function public.create_question_bank_set(
  p_folder_id bigint,
  p_set_name text
)
returns public.question_bank_sets
language plpgsql security definer set search_path=public
as $$
declare r public.question_bank_sets;
begin
  if auth.uid() is null then raise exception 'Admin login required'; end if;
  insert into public.question_bank_sets(folder_id,set_name)
  values(p_folder_id,trim(p_set_name))
  on conflict(folder_id,set_name) do update set set_name=excluded.set_name
  returning * into r;
  return r;
end;
$$;

grant execute on function public.create_question_bank_folder(text,text) to authenticated;
grant execute on function public.create_question_bank_set(bigint,text) to authenticated;

-- ============================================================
-- ৬) Student-safe exam questions remain served by the existing
--    get_public_exam_questions RPC. It must read exam_questions,
--    never expose correct_answer, folder_id or set_id.
-- ============================================================

-- NOTE:
-- এই migration কোনো পুরোনো Question/Exam delete করে না।
-- Exam থেকে Question remove করলে শুধু exam_questions row মুছবে।
-- Master Question public.questions-এ থাকবে।
