create table if not exists public.site_visitors (id bigint generated by default as identity primary key, visitor_key text not null unique, first_seen timestamptz not null default now(), last_seen timestamptz not null default now());
alter table public.site_visitors enable row level security;
drop policy if exists site_visitors_public_insert on public.site_visitors; create policy site_visitors_public_insert on public.site_visitors for insert to anon with check (visitor_key is not null and length(visitor_key) between 10 and 100);
drop policy if exists site_visitors_public_update on public.site_visitors; create policy site_visitors_public_update on public.site_visitors for update to anon using (visitor_key is not null) with check (visitor_key is not null and length(visitor_key) between 10 and 100);
drop policy if exists site_visitors_admin_read on public.site_visitors; create policy site_visitors_admin_read on public.site_visitors for select to authenticated using (true);
create index if not exists site_visitors_last_seen_idx on public.site_visitors(last_seen);
